export enum ROLES_ENUM {
    ADMIN_DCORE = '1',
    CHOFER = '3',
    SUPERVISOR = '4',
    ADMIN = '5',
    USER_JURIDICO = '7',
    TRANSPORTE = '8',
    TECN_JURIDICO = '9',
    PEONETA = '10',
    USER_NATURAL = '11',
    FINANZA = '12',
    JEFE_OPERACIONES = '13',
    JEFE_TRANSPORTE = '14',
    COORDINADOR = '15',
    SEGURIDAD = '16',
    JEFE_FINANZAS = '17',
    PICKING = '18',
    PICKEADOR_TIENDA = '19',
    TOC = '20',
    RUT_PICKEADOR = '21',
    JEFE_TOC = '22',
    RAUDDY = '23',
    ANALISTA_EXO = '30',
    CLIENTE_RSV = '40',
    OPERARIO_RSV = '42',
    ADMINISTRATIVO_RSV = '43',
    SUPERVISOR_RSV = '44',
    NROL_RSV = '45'

}