import {
  cilDevices,
  cilSwapHorizontal,
  cilWindow,
  cilClipboard,
  cilMenu,
  cilBuilding,
  cilTruck,
  cilContact,
  cilBarChart,
  cilCalendar,
  cilChart,
  cilCheck,
  cilCloudDownload,
  cilHome,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMoon,
  cilPeople,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilSpeedometer,
  cilTags,
  cilUser,
  cilCarAlt,
  cilAccountLogout,
  cilPlus,
  cilMinus,
  cilChatBubble,
  cilHandshake
} from '@coreui/icons';



// const iViking = 
export const iconSubset = {
  cilHandshake,
  cilDevices,
  cilSwapHorizontal,
  cilWindow,
  cilMenu,
  cilClipboard,
  cilBuilding,
  cilTruck,
  cilContact,
  cilCalendar,
  cilChart,
  cilCheck,
  cilCloudDownload,
  cilHome,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMoon,
  cilPeople,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilSpeedometer,
  cilTags,
  cilUser,
  cilCarAlt,
  cilAccountLogout,
  cilPlus,
  cilMinus,
  cilBarChart,
  cilChatBubble
};

export enum IconSubset { 
  cilMenu = 'cilMenu',
  cilChatBubble = 'cilChatBubble',
  cilClipboard = 'cilClipboard',
  cilBuilding = 'cilBuilding',
  cilTruck = 'cilTruck',
  cilContact = 'cilContact',
  cilCalendar = 'cilCalendar',
  cilChart = 'cilChart',
  cilCheck='cilCheck',
  cilCloudDownload = 'cilCloudDownload',
  cilHome = 'cilHome',
  cilLockLocked = 'cilLockLocked',
  cilMagnifyingGlass = 'cilMagnifyingGlass',
  cilMoon = 'cilMoon',
  cilPeople = 'cilPeople',
  cilReportSlash = 'cilReportSlash',
  cilSave = 'cilSave',
  cilSettings = 'cilSettings',
  cilSpeedometer = 'cilSpeedometer',
  cilTags = 'cilTags',
  cilUser = 'cilUser',
  cilAccountLogout = "cilAccountLogout",
  cilPlus = "cilPlus",
  cilMinus = "cilMinus",
  cilBarChart = "cilBarChart"
}
