import {
  cilFindInPage,
  cilClipboard,
  cilBuilding,
  cilTruck,
  cilContact,
  cilBarChart,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilBookmark,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilCloudDownload,
  cilCode,
  cilCreditCard,
  cilCursor,
  cilDollar,
  cilDrop,
  cilFile,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilList,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMenu,
  cilMoon,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilTags,
  cilTask,
  cilTrash,
  cilUser,
  cilArrowCircleBottom,
  cilCarAlt,
  cilAccountLogout,
  cilPlus,
  cilMinus,
  cilDelete,
  cilChatBubble
} from '@coreui/icons';

export const iconSubset = {
  cilFindInPage,
  cilClipboard,
  cilBuilding,
  cilTruck,
  cilContact,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilBookmark,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilCloudDownload,
  cilCode,
  cilCreditCard,
  cilCursor,
  cilDollar,
  cilDrop,
  cilFile,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilList,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMenu,
  cilMoon,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilTags,
  cilTask,
  cilTrash,
  cilUser,
  cilArrowCircleBottom,
  cilCarAlt,
  cilAccountLogout,
  cilPlus,
  cilMinus,
  cilDelete,
  cilBarChart,
  cilChatBubble
};

export enum IconSubset { 
  cilChatBubble = 'cilChatBubble',
  cilFindInPage = 'cilFindInPage',
  cilClipboard = 'cilClipboard',
  cilBuilding = 'cilBuilding',
  cilTruck = 'cilTruck',
  cilContact = 'cilContact',
  cilAlignCenter = 'cilAlignCenter',
  cilAlignLeft = 'cilAlignLeft',
  cilAlignRight = 'cilAlignRight',
  cilArrowBottom = 'cilArrowBottom',
  cilArrowRight = 'cilArrowRight',
  cilArrowTop = 'cilArrowTop',
  cilBookmark = 'cilBookmark',
  cilCalendar = 'cilCalendar',
  cilChart = 'cilChart',
  cilChartPie = 'cilChartPie',
  cilCheck='cilCheck',
  cilCloudDownload = 'cilCloudDownload',
  cilCode = 'cilCode',
  cilCreditCard = 'cilCreditCard',
  cilCursor = 'cilCursor',
  cilDollar = 'cilDollar',
  cilDrop = 'cilDrop',
  cilFile = 'cilFile',
  cilHome = 'cilHome',
  cilInbox = 'cilInbox',
  cilIndentDecrease = 'cilIndentDecrease',
  cilIndentIncrease = 'cilIndentIncrease',
  cilItalic = 'cilItalic',
  cilJustifyCenter = 'cilJustifyCenter',
  cilList = 'cilList',
  cilLocationPin = 'cilLocationPin',
  cilLockLocked = 'cilLockLocked',
  cilMagnifyingGlass = 'cilMagnifyingGlass',
  cilMenu = 'cilMenu',
  cilMoon = 'cilMoon',
  cilNotes = 'cilNotes',
  cilOptions = 'cilOptions',
  cilPaperclip = 'cilPaperclip',
  cilPaperPlane = 'cilPaperPlane',
  cilPen = 'cilPen',
  cilPencil = 'cilPencil',
  cilPeople = 'cilPeople',
  cilPuzzle = 'cilPuzzle',
  cilReportSlash = 'cilReportSlash',
  cilSave = 'cilSave',
  cilSettings = 'cilSettings',
  cilSpeech = 'cilSpeech',
  cilSpeedometer = 'cilSpeedometer',
  cilSpreadsheet = 'cilSpreadsheet',
  cilStar = 'cilStar',
  cilTags = 'cilTags',
  cilTask = 'cilTask',
  cilTrash = 'cilTrash',
  cilUser = 'cilUser',
  cilArrowCircleBottom = "cilArrowCircleBottom",
  cilAccountLogout = "cilAccountLogout",
  cilPlus = "cilPlus",
  cilMinus = "cilMinus",
  cilDelete = "cilDelete",
  cilBarChart = "cilBarChart"
}
