import {ROLES_ENUM} from  './models/enum/roles.enum'

export const ROLES_PERMITIDOS = {
    LOGIN_NOT_ALLOW : [ROLES_ENUM.USER_JURIDICO, ROLES_ENUM.USER_NATURAL],
    DASHBOARD : [ROLES_ENUM.ADMIN, ROLES_ENUM.JEFE_FINANZAS, ROLES_ENUM.JEFE_TRANSPORTE, ROLES_ENUM.JEFE_OPERACIONES,ROLES_ENUM.TRANSPORTE],
    TRANSPORTE : [ROLES_ENUM.ADMIN, ROLES_ENUM.JEFE_TRANSPORTE, ROLES_ENUM.CHOFER,ROLES_ENUM.TRANSPORTE],
    OPERACIONES : [ROLES_ENUM.ADMIN, ROLES_ENUM.JEFE_OPERACIONES],
    PICKING : [ROLES_ENUM.ADMIN],
    OPL  : [ROLES_ENUM.ADMIN],
    RECEPCION : [ROLES_ENUM.ADMIN,ROLES_ENUM.PICKING, ROLES_ENUM.JEFE_OPERACIONES],
    PANEL : [ROLES_ENUM.ADMIN]
}


export const ACCESO_ROL : any = {
    [ROLES_ENUM.ADMIN_DCORE] : 'dashboard',
    [ROLES_ENUM.CHOFER] : 'transporte/reportes',
    [ROLES_ENUM.SUPERVISOR] : 'dashboard',
    [ROLES_ENUM.ADMIN] : 'dashboard',
    [ROLES_ENUM.TRANSPORTE] : 'dashboard',
    [ROLES_ENUM.JEFE_OPERACIONES] : 'dashboard',
    [ROLES_ENUM.JEFE_TRANSPORTE] : 'dashboard',
    [ROLES_ENUM.PICKING]: 'recepcion/easy-opl'
}